# run the playbook as:
#
# ansible-playbook playbook.yml -i hosts.ini --become-user=root --ask-become-pass
---
- hosts: local_host   
  vars_files:
  - gpgVar.yml

  tasks:
    - name: Ensure .gnupg config directory exists with right permissions
      ansible.builtin.file:
        dest: "{{ gpg_home }}/.gnupg"
        state: directory
        mode: "0700"
        owner: "{{ gpg_generator_user }}"   
    
    - name: Copy default template for gpg key generation
      ansible.builtin.template:
        src: templates/gpgGenKeyScript
        dest: "{{ gpg_home }}/.gnupg/gen-key-script-{{ gpg_user }}"
        mode: "0600"
        owner: "{{ gpg_generator_user }}"   
        
    - name: Generate gpg key
      ansible.builtin.command: "gpg --batch --gen-key {{ gpg_home }}/.gnupg/gen-key-script-{{ gpg_user }}"
      become: yes
      become_user: "{{ gpg_generator_user }}"
      args:
        chdir: "{{ gpg_home }}"        
    
    - name: Get user armored public key
      ansible.builtin.shell: "gpg --export -a {{ gpg_useremail }} > {{ gpg_home }}/{{ gpg_pubkeyfileexport }}"
      become: yes
      become_user: "{{ gpg_generator_user }}"
      args:
        creates: "{{ gpg_home }}/{{ gpg_pubkeyfileexport }}"


- hosts: HashicorpVault 
  vars_files:
  - gpgVar.yml

  tasks:
    - name: Export GPG Public Key.
      ansible.builtin.copy:
        dest: "/tmp/{{ gpg_user }}.pub"        
        content: "/home/{{ gpg_generator_user }}/vaultBackup/{{ gpg_user }}.pub"

    - name: Import Public Key
      ansible.builtin.command: gpg --import "/tmp/{{ gpg_user }}.pub" 
           

