local_host:
  hosts:
    localhost: 
      ansible_port: 22 
      ansible_user: admin 
      ansible_password: zyxpo0-boKsyz-wuqqah 
      ansible_host: 127.0.0.1
  vars:
    ssh_key_filename: "ansible_rsa"
    remote_machine_username: "admin"
    remote_machine_password: "zyxpo0-boKsyz-wuqqah"

HashicorpVault:
  hosts:
    Vault2: 
      ansible_port: 22 
      ansible_user: admin 
      ansible_host: HOST_IP
